<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="GDPR" nsURI="http://www.example.org/GDPR" nsPrefix="GDPR">
  <eClassifiers xsi:type="ecore:EClass" name="Processing">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputData" upperBound="-1"
        eType="#//Data"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputData" upperBound="-1"
        eType="#//Data"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="purpose" lowerBound="1"
        upperBound="-1" eType="#//Purpose"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="onTheBasisOf" lowerBound="1"
        upperBound="-1" eType="#//LegalBasis"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="followingProcessing" upperBound="-1"
        eType="#//Processing"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Collection" eSuperTypes="#//Processing"/>
  <eClassifiers xsi:type="ecore:EClass" name="Transfering" eSuperTypes="#//Processing"/>
  <eClassifiers xsi:type="ecore:EClass" name="Useage" eSuperTypes="#//Processing"/>
  <eClassifiers xsi:type="ecore:EClass" name="Storing" eSuperTypes="#//Processing"/>
  <eClassifiers xsi:type="ecore:EClass" name="Data"/>
  <eClassifiers xsi:type="ecore:EClass" name="PersonalData" eSuperTypes="#//Data">
    <eStructuralFeatures xsi:type="ecore:EReference" name="references" lowerBound="1"
        upperBound="-1" eType="#//NaturalPerson"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Purpose">
    <eStructuralFeatures xsi:type="ecore:EReference" name="decidedOver" lowerBound="1"
        eType="#//Controller"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LegalBasis">
    <eStructuralFeatures xsi:type="ecore:EReference" name="personaldata" eType="#//PersonalData"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PerformanceOfContract" eSuperTypes="#//LegalBasis">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contractingParty" lowerBound="2"
        upperBound="-1" eType="#//Role"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExerciceOfPublicAuthrity" eSuperTypes="#//LegalBasis"/>
  <eClassifiers xsi:type="ecore:EClass" name="Consent" eSuperTypes="#//LegalBasis">
    <eStructuralFeatures xsi:type="ecore:EReference" name="definedPurpose" lowerBound="1"
        upperBound="-1" eType="#//Purpose"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="proof" lowerBound="1" eType="#//Proof"
        eOpposite="#//Proof/consent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="consending" lowerBound="1"
        eType="#//NaturalPerson"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Proof">
    <eStructuralFeatures xsi:type="ecore:EReference" name="consent" lowerBound="1"
        eType="#//Consent" eOpposite="#//Consent/proof"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NaturalPerson" eSuperTypes="#//Role">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="birthdate" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Date"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Controller" eSuperTypes="#//Role">
    <eStructuralFeatures xsi:type="ecore:EReference" name="proof" upperBound="-1"
        eType="#//Proof" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ThirdParty" eSuperTypes="#//Role"/>
</ecore:EPackage>
